Change to storage-event.ts for compatibility with Angular 5
Change to storage-event.ts for compatibility with Angular 5

```
ERROR in node_modules/ngx-store/src/utility/storage/storage-event.d.ts(1,22): error TS2420: Class 'NgxStorageEvent' incorrectly implements interface 'StorageEvent'.
  Property 'NONE' is missing in type 'NgxStorageEvent'.
```

```
ERROR in node_modules/ngx-store/src/utility/storage/storage-event.d.ts(1,22): error TS2420: Class 'NgxStorageEvent' incorrectly implements interface 'StorageEvent'.
  Property 'oldValue' is optional in type 'NgxStorageEvent' but required in type 'StorageEvent'.
```